import { type BuydInputs } from "@/lib/buyd";

export type BuydScenario = {
  id: string;
  nameKey: string;
  descriptionKey: string;
  inputs: Partial<BuydInputs>;
};

export const buydScenarios: BuydScenario[] = [
  {
    id: "standard-re",
    nameKey: "buyd.scenarios.standard.name",
    descriptionKey: "buyd.scenarios.standard.description",
    inputs: {
      initialAssetValue: 450000,
      growthRatePercent: 3,
      incomeYieldPercent: 6,
      incomeGrowthRatePercent: 2,
      annualExpenses: 14000,
      expenseGrowthRatePercent: 2,
      initialDebt: 180000,
      interestRatePercent: 6.25,
      targetLtvPercent: 35,
      lenderMaxLtvPercent: 55,
      borrowMode: "maxSafe",
      yearlySpend: 20000,
      livingExpensesPerYear: 32000,
      cashBufferMonths: 6,
      years: 30,
      stressCrashEnabled: true,
      stressCrashYear: 3,
      stressCrashDropPercent: 25,
      stressRateSpikeEnabled: true,
      stressRateSpikeStartYear: 5,
      stressRateSpikeIncreasePercent: 2,
    },
  },
  {
    id: "conservative",
    nameKey: "buyd.scenarios.conservative.name",
    descriptionKey: "buyd.scenarios.conservative.description",
    inputs: {
      initialAssetValue: 400000,
      growthRatePercent: 2.5,
      incomeYieldPercent: 6.5,
      incomeGrowthRatePercent: 1.5,
      annualExpenses: 13000,
      expenseGrowthRatePercent: 2,
      initialDebt: 120000,
      interestRatePercent: 5.75,
      targetLtvPercent: 30,
      lenderMaxLtvPercent: 50,
      borrowMode: "fixed",
      yearlySpend: 15000,
      livingExpensesPerYear: 28000,
      cashBufferMonths: 9,
      years: 30,
      stressCrashEnabled: true,
      stressCrashYear: 4,
      stressCrashDropPercent: 20,
      stressRateSpikeEnabled: false,
    },
  },
  {
    id: "rate-shock",
    nameKey: "buyd.scenarios.rateShock.name",
    descriptionKey: "buyd.scenarios.rateShock.description",
    inputs: {
      initialAssetValue: 380000,
      growthRatePercent: 3,
      incomeYieldPercent: 5.5,
      incomeGrowthRatePercent: 1.5,
      annualExpenses: 15000,
      expenseGrowthRatePercent: 2.5,
      initialDebt: 200000,
      interestRatePercent: 7,
      targetLtvPercent: 40,
      lenderMaxLtvPercent: 60,
      borrowMode: "fixed",
      yearlySpend: 22000,
      livingExpensesPerYear: 36000,
      cashBufferMonths: 6,
      years: 30,
      stressCrashEnabled: false,
      stressRateSpikeEnabled: true,
      stressRateSpikeStartYear: 2,
      stressRateSpikeIncreasePercent: 4,
    },
  },
  {
    id: "income-shock",
    nameKey: "buyd.scenarios.incomeShock.name",
    descriptionKey: "buyd.scenarios.incomeShock.description",
    inputs: {
      initialAssetValue: 420000,
      growthRatePercent: 2.8,
      incomeYieldPercent: 6.2,
      incomeGrowthRatePercent: 1,
      annualExpenses: 16000,
      expenseGrowthRatePercent: 2,
      initialDebt: 170000,
      interestRatePercent: 6.5,
      targetLtvPercent: 35,
      lenderMaxLtvPercent: 55,
      borrowMode: "maxSafe",
      yearlySpend: 18000,
      livingExpensesPerYear: 30000,
      cashBufferMonths: 6,
      years: 30,
      stressIncomeShockEnabled: true,
      stressIncomeShockYear: 3,
      stressIncomeShockPercent: 15,
      stressExpenseShockEnabled: true,
      stressExpenseShockYear: 3,
      stressExpenseShockPercent: 20,
    },
  },
];
